### ISSUE TITLE
Get accouts on JADE

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo#53]
The UK Met office's Jade project has invite only access to a JupyterHub + Dask + Iris deployment on their hardware.  I think that the following XArray/JupyterHub/Dask developers might find this system interesting and informative to play with.  @jacobtomlinson if you're able to can I ask you to give the following github usernames access?

- @mrocklin
- @rabernat 
- @jhamman 
- @shoyer
- @yuvipanda
- @choldgraf

My understanding is that they have a single large Dask cluster accessible from a modified Zero-to-JupyterHub deployment. 

My apologies if anyone didn't want to be listed here.  Hopefully unanticipated access is not troublesome to anyone.  @jacobtomlinson seemed to suggest that they were pretty open to other people, so please feel free to nominate others.

**Comment by mrocklin** [comment]
http://www.informaticslab.co.uk/projects/jade.html

**Comment by mrocklin** [comment]
Some feedback for @jacobtomlinson .  I've given things 

1.  Would it be possible to install XArray?
2.  `!ls /s3` doesn't report anything for me
3.  The `DASK_SCHEDULER_ADDRESS` trick won't work until distributed 1.20.2 (you're currently at 1.20.1
4.  Is there a way to get access to Dask's diagnostic dashboard?

**Comment by jacobtomlinson** [comment]
1. We can add xarray no problem.
2. This is desired behaviour as there are potentially millions of buckets
on S3. If you ls an actual bucket you should see output.
3. Ah! I'll get that updated too.
4. dask-dashboard.informaticslab.co.uk

**Comment by mrocklin** [comment]
Can you recommend an example notebook to play with?  I have little experience with either XArray or Iris.

**Comment by mrocklin** [comment]
I sometimes get 502 errors when accessing the dashboard page.  The `workers/` page never works (though this is as likely my fault as Jade's :))

**Comment by mrocklin** [comment]
It is cool to see the autoscaling ability of the cluster.  

However sometimes when I quickly fill up a set of workers and new workers come on the data balance between them becomes unpleasant.  The scheduler ends up moving a lot of data between workers during computation.  We should consider a couple of small changes on the Dask side:

1.  Quickly spin up to a target number of workers based on estimated load
2.  Move data around in the background when the cluster is quiet

Also I'm curious, how long does the scheduler stay up?  Do things ever fall over?

**Comment by rabernat** [comment]
I would like to try out JADE, but I'm not sure how to log in.

**Comment by mrocklin** [comment]
@rabernat check your e-mail

**Comment by mrocklin** [comment]
Trying to read some CSV data using the FUSE system was unpleasant.  It took a decent amount of time, and had difficulty reading a file block-wise.

```python
distributed.utils - ERROR - [Errno 14] Bad address
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/distributed/utils.py", line 238, in f
    result[0] = yield make_coro()
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/conda/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/opt/conda/lib/python3.6/site-packages/distributed/client.py", line 1304, in _gather
    traceback)
  File "/opt/conda/lib/python3.6/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.6/site-packages/dask/bytes/core.py", line 211, in read_block_from_file
    return read_block(f, off, bs, delimiter)
  File "/opt/conda/lib/python3.6/site-packages/dask/bytes/utils.py", line 207, in read_block
    seek_delimiter(f, delimiter, 2**16)
  File "/opt/conda/lib/python3.6/site-packages/dask/bytes/utils.py", line 148, in seek_delimiter
    current = file.read(blocksize)
OSError: [Errno 14] Bad address
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-10-9e112543b788> in <module>()
----> 1 len(df)

/opt/conda/lib/python3.6/site-packages/dask/dataframe/core.py in __len__(self)
    409     def __len__(self):
    410         return self.reduction(len, np.sum, token='len', meta=int,
--> 411                               split_every=False).compute()
    412 
    413     @insert_meta_param_description(pad=12)

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute(self, **kwargs)
    133         dask.base.compute
    134         """
--> 135         (result,) = compute(self, traverse=False, **kwargs)
    136         return result
    137 

/opt/conda/lib/python3.6/site-packages/dask/base.py in compute(*args, **kwargs)
    331     postcomputes = [a.__dask_postcompute__() if is_dask_collection(a)
    332                     else (None, a) for a in args]
--> 333     results = get(dsk, keys, **kwargs)
    334     results_iter = iter(results)
    335     return tuple(a if f is None else f(next(results_iter), *a)

/opt/conda/lib/python3.6/site-packages/distributed/client.py in get(self, dsk, keys, restrictions, loose_restrictions, resources, sync, asynchronous, **kwargs)
   1986                 secede()
   1987             try:
-> 1988                 results = self.gather(packed, asynchronous=asynchronous)
   1989             finally:
   1990                 for f in futures.values():

/opt/conda/lib/python3.6/site-packages/distributed/client.py in gather(self, futures, errors, maxsize, direct, asynchronous)
   1424             return self.sync(self._gather, futures, errors=errors,
   1425                              direct=direct, local_worker=local_worker,
-> 1426                              asynchronous=asynchronous)
   1427 
   1428     @gen.coroutine

/opt/conda/lib/python3.6/site-packages/distributed/client.py in sync(self, func, *args, **kwargs)
    568             return future
    569         else:
--> 570             return sync(self.loop, func, *args, **kwargs)
    571 
    572     def __repr__(self):

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in sync(loop, func, *args, **kwargs)
    252             e.wait(1000000)
    253     if error[0]:
--> 254         six.reraise(*error[0])
    255     else:
    256         return result[0]

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/opt/conda/lib/python3.6/site-packages/distributed/utils.py in f()
    236             yield gen.moment
    237             thread_state.asynchronous = True
--> 238             result[0] = yield make_coro()
    239         except Exception as exc:
    240             logger.exception(exc)

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1053 
   1054                     try:
-> 1055                         value = future.result()
   1056                     except Exception:
   1057                         self.had_exception = True

/opt/conda/lib/python3.6/site-packages/tornado/concurrent.py in result(self, timeout)
    236         if self._exc_info is not None:
    237             try:
--> 238                 raise_exc_info(self._exc_info)
    239             finally:
    240                 self = None

/opt/conda/lib/python3.6/site-packages/tornado/util.py in raise_exc_info(exc_info)

/opt/conda/lib/python3.6/site-packages/tornado/gen.py in run(self)
   1061                     if exc_info is not None:
   1062                         try:
-> 1063                             yielded = self.gen.throw(*exc_info)
   1064                         finally:
   1065                             # Break up a reference to itself

/opt/conda/lib/python3.6/site-packages/distributed/client.py in _gather(self, futures, errors, direct, local_worker)
   1302                             six.reraise(type(exception),
   1303                                         exception,
-> 1304                                         traceback)
   1305                     if errors == 'skip':
   1306                         bad_keys.add(key)

/opt/conda/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    690                 value = tp()
    691             if value.__traceback__ is not tb:
--> 692                 raise value.with_traceback(tb)
    693             raise value
    694         finally:

/opt/conda/lib/python3.6/site-packages/dask/bytes/core.py in read_block_from_file()
    209 def read_block_from_file(lazy_file, off, bs, delimiter):
    210     with lazy_file as f:
--> 211         return read_block(f, off, bs, delimiter)
    212 
    213 

/opt/conda/lib/python3.6/site-packages/dask/bytes/utils.py in read_block()
    205         try:
    206             f.seek(start + length)
--> 207             seek_delimiter(f, delimiter, 2**16)
    208         except ValueError:
    209             f.seek(0, 2)

/opt/conda/lib/python3.6/site-packages/dask/bytes/utils.py in seek_delimiter()
    146     last = b''
    147     while True:
--> 148         current = file.read(blocksize)
    149         if not current:
    150             return

OSError: [Errno 14] Bad address
```

I would like to to try `s3fs`, but that Python module is not loaded.  In general we need to figure out a nice way to allow for configurable environments.

**Comment by mrocklin** [comment]
To be clear, I'm totally outside of the expected use case for JADE.  My goal is to break things, not to set expectations that these things should be fixed or set expectations that these should have existed previously.

**Comment by jacobtomlinson** [comment]
@mrocklin 

- The scheduler generally stays up permanently. Often between deployments it can runs for days/weeks.
- Sometimes it does fall over, but I can't think of any examples right now.
- Yes we should try s3fs too and compare with pysssix.
- It would be great if the number of workers could jump to the right amount instead of having to double each time. We would still have issues if that total number exceeded the capacity of the cluster and caused the infrastructure to scale, there would then be a step change in the number of workers.
- Not sure about the 502s. I did notice the workers page broke with my last upgrade. But potentially another upgrade will fix.
